name: questscrolls
main: com.king.Zhu
version: 5.1

softdepend:
  - PlaceholderAPI

commands:
  questscrolls:
    description: 这是一个默认的指令
    usage: /questscrolls
    permission: <plugin name>.set
    permission-message: 你需要 <permission> 权限

permissions:
  questscrolls.set:
    description: administrator
    default: op